# Bayesian regression to predict gestational age in second and third trimester maternal plasma proteomics data

Provides:
- Mean predictions (expected value of gestational age)<br/>
- Credible intervals (e.g., 95% probability gestational age falls within [a, b])<br/>

In [1]:
import pandas as pd

In [2]:
second_trimester = pd.read_csv('../output/tarca_et_al_2021/norm_log2t_batch_corrected_integrated_dataset_second_trimester.csv')
second_trimester

         Accession GEO_accession    Group  GA_delivery  Target   Log2RFU
0       GSM4525301     GSE150167  Control         40.1  14-3-3  0.835382
1       GSM4525302     GSE150167     sPTD         34.1  14-3-3  0.822620
2       GSM4525303     GSE150167    PPROM         36.7  14-3-3  0.834636
3       GSM4525304     GSE150167     sPTD         35.0  14-3-3  0.850609
4       GSM4525305     GSE150167     sPTD         36.0  14-3-3  0.822708
...            ...           ...      ...          ...     ...       ...
433375  GSM6254820     GSE206454  Control          NaN     vWF  0.991198
433376  GSM6254821     GSE206454  Control          NaN     vWF  0.993465
433377  GSM6254823     GSE206454  Control          NaN     vWF  1.003324
433378  GSM6254828     GSE206454  Control          NaN     vWF  1.005959
433379  GSM6254829     GSE206454  Control          NaN     vWF  0.985670

[433380 rows x 6 columns]

In [3]:
third_trimester = pd.read_csv('../output/tarca_et_al_2021/norm_log2t_batch_corrected_integrated_dataset_third_trimester.csv')
third_trimester

         Accession GEO_accession    Group  GA_delivery  Target   Log2RFU
0       GSM4525406     GSE150167  Control         40.1  14-3-3  0.854517
1       GSM4525407     GSE150167     sPTD         34.1  14-3-3  0.853892
2       GSM4525408     GSE150167    PPROM         36.7  14-3-3  0.853894
3       GSM4525409     GSE150167     sPTD         35.0  14-3-3  0.865530
4       GSM4525410     GSE150167     sPTD         36.0  14-3-3  0.861809
...            ...           ...      ...          ...     ...       ...
379785  GSM6254825     GSE206454  Control          NaN     vWF  1.000289
379786  GSM6254826     GSE206454  Control          NaN     vWF  0.982881
379787  GSM6254827     GSE206454  Control          NaN     vWF  0.990403
379788  GSM6254830     GSE206454  Control          NaN     vWF  1.002559
379789  GSM6254832     GSE206454  Control          NaN     vWF  1.004912

[379790 rows x 6 columns]

In [4]:
percentile_targets = ["IL-17B", "OX40 Ligand", "FGF-12", "DSC3", "NANOG", "IL-12", "RTN4", "DcR3", "IgG", "HPV E7 Type 16", "D-dimer", "TNR4", "CD70", "FGF-12", "NKp30", "GPC2", "SSRP1", "EG-VEGF", "Arylsulfatase A", "STX1a"]
pca_targets = ["PKC-B-II", "JAK2", "Cyclophilin A", "P-Selectin", "IGFBP-6", "Soggy-1", "FER", "a2-Macroglobulin", "Thrombin", "PKC-A", "STX1a", "Cadherin-6", "PCSK7"]
both = ["IL-17B", "OX40 Ligand", "FGF-12", "DSC3", "NANOG", "IL-12", "RTN4", "DcR3", "IgG", "HPV E7 Type 16", "D-dimer", "TNR4", "CD70", "FGF-12", "NKp30", "GPC2", "SSRP1", "EG-VEGF", "Arylsulfatase A", "STX1a", "PKC-B-II", "JAK2", "Cyclophilin A", "P-Selectin", "IGFBP-6", "Soggy-1", "FER", "a2-Macroglobulin", "Thrombin", "PKC-A", "STX1a", "Cadherin-6", "PCSK7"]

In [5]:
second_trimester_pca = second_trimester.loc[second_trimester['Target'].isin(pca_targets)]
third_trimester_pca = third_trimester.loc[third_trimester['Target'].isin(pca_targets)]
third_trimester_pca

second_trimester_percentiles = second_trimester.loc[second_trimester['Target'].isin(percentile_targets)]
third_trimester_percentiles = third_trimester.loc[third_trimester['Target'].isin(percentile_targets)]
third_trimester_percentiles

second_trimester_both = second_trimester.loc[second_trimester['Target'].isin(both)]
third_trimester_both = third_trimester.loc[third_trimester['Target'].isin(both)]
third_trimester_both

,Accession,GEO_accession,Group,GA_delivery,Target,Log2RFU
25428,GSM4525406,GSE150167,Control,40.1,Arylsulfatase A,1.051548
25429,GSM4525407,GSE150167,sPTD,34.1,Arylsulfatase A,1.067005
25430,GSM4525408,GSE150167,PPROM,36.7,Arylsulfatase A,1.077536
25431,GSM4525409,GSE150167,sPTD,35.0,Arylsulfatase A,1.060784
25432,GSM4525410,GSE150167,sPTD,36.0,Arylsulfatase A,1.054635
...,...,...,...,...,...,...
359899,GSM6254825,GSE206454,Control,NaN,a2-Macroglobulin,0.989030
359900,GSM6254826,GSE206454,Control,NaN,a2-Macroglobulin,0.990909
359901,GSM6254827,GSE206454,Control,NaN,a2-Macroglobulin,0.980831
359902,GSM6254830,GSE206454,Control,NaN,a2-Macroglobulin,0.991725
359903,GSM6254832,GSE206454,Control,NaN,a2-Macroglobulin,0.996873

In [6]:
import preprocess_model_data

full_data_pca = preprocess_model_data.process_model_data(second_trimester_pca, third_trimester_pca, model = 'ga')
full_data_percentile = preprocess_model_data.process_model_data(second_trimester_percentiles, third_trimester_percentiles, model = 'ga')
full_data_both = preprocess_model_data.process_model_data(second_trimester_both, third_trimester_both, model = 'ga')
full_data_both

c:\Users\doram\Desktop\Masters\RP-2\code\preprocess_model_data.py:31: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  second_trimester_data.loc[:, 'Group'] = second_trimester_data['Group'].replace(mapping)
c:\Users\doram\Desktop\Masters\RP-2\code\preprocess_model_data.py:32: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  third_trimester_data.loc[:, 'Group'] = third_trimester_data['Group'].replace(mapping)
c:\Users\doram\Desktop\Masters\RP-2\code\preprocess_model_data.py:31: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  second_trimester_data.loc[:, 'Group'] = second_trimester_data['Group'].replace(mapping)
c:\Users\doram\Desktop\Masters\RP-2\code\preprocess_model_data.py:32: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  third_trimester_data.loc[:, 'Group'] = third_trimester_data['Group'].replace(mapping)
c:\Users\doram\Desktop\Masters\RP-2\code\preprocess_model_data.py:31: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  second_trimester_data.loc[:, 'Group'] = second_trimester_data['Group'].replace(mapping)
c:\Users\doram\Desktop\Masters\RP-2\code\preprocess_model_data.py:32: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  third_trimester_data.loc[:, 'Group'] = third_trimester_data['Group'].replace(mapping)

,GA_delivery,Trimester,Accession,Arylsulfatase A,CD70,Cadherin-6,Cyclophilin A,D-dimer,DSC3,DcR3,...,PCSK7,PKC-A,PKC-B-II,RTN4,SSRP1,STX1a,Soggy-1,TNR4,Thrombin,a2-Macroglobulin
0,40.1,2,GSM4525301,1.043256,1.052710,0.988457,1.000590,0.831140,1.008708,1.006780,...,1.002599,1.004450,0.965419,0.833489,0.987989,1.002848,0.995650,0.996671,0.951813,0.988284
31,34.1,2,GSM4525302,1.062509,1.045000,1.001295,1.005451,0.834700,0.990605,1.000270,...,0.980722,0.993733,0.954534,0.829208,0.996457,1.016846,1.011726,0.995480,1.034752,1.015361
62,35.0,2,GSM4525304,1.062763,1.045757,1.001962,1.008365,0.835665,0.994825,1.002125,...,0.973848,0.989681,0.953789,0.849283,0.998393,1.022131,1.013850,0.999189,1.058254,1.021588
93,36.0,2,GSM4525305,1.061352,1.042170,1.001582,1.006750,0.832885,0.994783,1.007848,...,0.976242,0.991831,0.954745,0.830801,0.999909,1.015848,1.011724,1.001196,1.035236,1.016439
124,32.9,2,GSM4525306,1.075312,1.050280,1.000403,1.006412,0.833944,0.988487,0.997550,...,0.976431,0.993394,0.956954,0.820936,1.019100,1.022220,1.011671,1.018708,1.039294,1.012538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21235,NaN,3,GSM6254825,1.053102,1.048318,0.990014,1.002559,0.851229,1.007746,1.003926,...,1.004034,1.004412,0.968901,0.848364,0.986617,0.998996,0.998723,0.993322,0.943728,0.989030
21266,NaN,3,GSM6254826,1.042685,1.047435,0.984815,1.001796,0.843735,1.006068,1.006439,...,0.996726,0.999784,0.966902,0.833115,0.984930,0.996074,0.993251,0.994210,0.931702,0.990909
21297,NaN,3,GSM6254827,1.041246,1.050717,0.989154,1.004170,0.847539,1.002487,1.000667,...,1.007220,1.002148,0.963049,0.840855,0.984361,1.002284,1.001805,0.992158,0.914785,0.980831
21328,NaN,3,GSM6254830,1.050493,1.057914,0.989096,0.995317,0.858987,1.011601,1.010127,...,1.012892,0.994614,0.959784,0.864151,0.989097,1.001359,0.999898,0.998397,0.945920,0.991725
21359,NaN,3,GSM6254832,1.057248,1.057903,0.987313,0.995917,0.854804,1.007600,1.008760,...,1.003999,1.002466,0.957552,0.855640,0.989667,1.002233,1.001021,0.999106,0.951471,0.996873

In [7]:
#full_data_pca
#full_data_percentile

# Model building

In [8]:
# Subset the data for inference
# Create bins (quartiles) based on GA_delivery values
full_data_pca['GA_bin'] = pd.qcut(full_data_pca['GA_delivery'], q=4, duplicates='drop')
# Stratified sampling: pick 2 samples per GA bin for inference
inference_samples_pca = (
    full_data_pca.groupby('GA_bin', group_keys=False)
    .sample(n=2, random_state=42)
)
# Remove inference samples from the original dataset and drop helper bin column
full_data_pca2 = full_data_pca.drop(inference_samples_pca.index).drop(columns='GA_bin')

full_data_percentile['GA_bin'] = pd.qcut(full_data_percentile['GA_delivery'], q=4, duplicates='drop')
inference_samples_percentile = (
    full_data_percentile.groupby('GA_bin', group_keys=False)
    .sample(n=2, random_state=42)
)
full_data_percentile2 = full_data_percentile.drop(inference_samples_percentile.index).drop(columns='GA_bin')

full_data_both['GA_bin'] = pd.qcut(full_data_both['GA_delivery'], q=4, duplicates='drop')
inference_samples_both = (
    full_data_both.groupby('GA_bin', group_keys=False)
    .sample(n=5, random_state=42)
)
full_data_both2 = full_data_both.drop(inference_samples_both.index).drop(columns='GA_bin')

C:\Users\doram\AppData\Local\Temp\ipykernel_26280\202368719.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  full_data_pca.groupby('GA_bin', group_keys=False)
C:\Users\doram\AppData\Local\Temp\ipykernel_26280\202368719.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  full_data_percentile.groupby('GA_bin', group_keys=False)
C:\Users\doram\AppData\Local\Temp\ipykernel_26280\202368719.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  full_data_both.groupby('GA_bin', group_keys=False)

In [9]:
num_nans = full_data_pca2['GA_delivery'].isna().sum()
print(f'Number of NaNs in target (GestationalAge): {num_nans}')

Number of NaNs in target (GestationalAge): 488

In [10]:
X_pca = full_data_pca2.drop(columns=['Accession', 'GA_delivery']).values  # Drop sample ID and target columns
y_pca = full_data_pca2['GA_delivery'].values                              # the targets are continuous

X_perc = full_data_percentile2.drop(columns=['Accession', 'GA_delivery']).values  # Drop sample ID and target columns
y_perc = full_data_percentile2['GA_delivery'].values                              # the targets are continuous

X_both = full_data_both2.drop(columns=['Accession', 'GA_delivery']).values  # Drop sample ID and target columns
y_both = full_data_both2['GA_delivery'].values                              # the targets are continuous

In [11]:
import pandas as pd
import pymc as pm
import arviz as az
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_pca)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_pca, test_size=0.2, random_state=42)

WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install gxx`
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.

In [12]:
import pymc as pm
import pymc_bart as pmb

In [13]:
with pm.Model() as bart_model:
    # BART prior, automatically handles non-linearity
    mu = pmb.BART('mu', X_train, y_train)
    sigma = pm.HalfNormal('sigma', sigma=1)
    
    y_obs = pm.Normal('y_obs', mu=mu, sigma=sigma, observed=y_train)
    bart_trace = pm.sample(1000, tune=1000, random_seed=42, progressbar=True)

c:\Users\doram\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymc\model\core.py:1300: ImputationWarning: Data in y_obs contains missing values and will be automatically imputed from the sampling distribution.
  warnings.warn(impute_message, ImputationWarning)
Multiprocess sampling (4 chains in 4 jobs)
CompoundStep
>PGBART: [mu]
>NUTS: [sigma, y_obs_unobserved]

Output()

ParallelSamplingError: Chain 1 failed with: Bad initial energy: SamplerWarning(kind=<WarningType.BAD_ENERGY: 8>, message='Bad initial energy, check any log probabilities that are inf or -inf, nan or very small:\n[nan nan]\n.Try model.debug() to identify parametrization problems.', level='critical', step=0, exec_info=None, extra=None, divergence_point_source=None, divergence_point_dest=None, divergence_info=None)

In [ ]:
with model:
    posterior_preds = pm.sample_posterior_predictive(trace, var_names=['mu'])

In [ ]:
import numpy as np
# Get posterior mean predictions
y_pred = posterior_preds['mu'].mean(axis=0)

from sklearn.metrics import r2_score, mean_squared_error
print("R^2:", r2_score(y_train, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_train, y_pred)))