In [1]:
import pandas as pd

In [5]:
second_trimester_data = pd.read_csv('../output/tarca_et_al_2021/norm_log2t_batch_corrected_integrated_dataset_second_trimester.csv')
second_trimester_data

third_trimester_data = pd.read_csv('../output/tarca_et_al_2021/norm_log2t_batch_corrected_integrated_dataset_third_trimester.csv')
third_trimester_data

         Accession GEO_accession    Group  GA_delivery  Target   Log2RFU
0       GSM4525406     GSE150167  Control         40.1  14-3-3  0.854517
1       GSM4525407     GSE150167     sPTD         34.1  14-3-3  0.853892
2       GSM4525408     GSE150167    PPROM         36.7  14-3-3  0.853894
3       GSM4525409     GSE150167     sPTD         35.0  14-3-3  0.865530
4       GSM4525410     GSE150167     sPTD         36.0  14-3-3  0.861809
...            ...           ...      ...          ...     ...       ...
379785  GSM6254825     GSE206454  Control          NaN     vWF  1.000289
379786  GSM6254826     GSE206454  Control          NaN     vWF  0.982881
379787  GSM6254827     GSE206454  Control          NaN     vWF  0.990403
379788  GSM6254830     GSE206454  Control          NaN     vWF  1.002559
379789  GSM6254832     GSE206454  Control          NaN     vWF  1.004912

[379790 rows x 6 columns]

In [7]:
# Remove PPROM samples
# second_trimester_data = second_trimester_data[second_trimester_data['Group'] != "PPROM"]
# third_trimester_data = third_trimester_data[third_trimester_data['Group'] != "PPROM"]

# # Change group labels to numbers
# second_trimester_data['Group'].replace(to_replace = 'Control', value = 0, inplace=True)
# second_trimester_data['Group'].replace(to_replace = 'sPTD', value = 1, inplace=True)
# third_trimester_data['Group'].replace(to_replace = 'Control', value = 0, inplace=True)
# third_trimester_data['Group'].replace(to_replace = 'sPTD', value = 1, inplace=True)
       
# # Pivot the data into a wide format
# second_trimester_wide = second_trimester_data.pivot(index = 'Accession', columns = 'Target', values = 'Log2RFU')
# third_trimester_wide = third_trimester_data.pivot(index = 'Accession', columns = 'Target', values = 'Log2RFU')
    
# # Merge with the original data to include relevant columns
# second_trimester_model = pd.merge(second_trimester_wide, second_trimester_data, on='Accession', how='inner')
# third_trimester_model = pd.merge(third_trimester_wide, third_trimester_data, on='Accession', how='inner')
third_trimester_model

,Accession,14-3-3,17-beta-HSD 1,3HIDH,4-1BB,4-1BB ligand,40S ribosomal protein SA,41,4EBP2,6-Phosphogluconate dehydrogenase,...,tPA,tau,"transcription factor MLR1, isoform CRA_b",uPA,vWF,GEO_accession,Group,GA_delivery,Target,Log2RFU
0,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,0.976927,...,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0,40.1,14-3-3,0.854517
1,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,0.976927,...,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0,40.1,17-beta-HSD 1,1.050371
2,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,0.976927,...,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0,40.1,3HIDH,1.018176
3,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,0.976927,...,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0,40.1,4-1BB,1.014938
4,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,0.976927,...,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0,40.1,4-1BB ligand,1.038545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375125,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,0.946968,...,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0,NaN,tPA,0.967156
375126,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,0.946968,...,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0,NaN,tau,1.055996
375127,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,0.946968,...,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0,NaN,"transcription factor MLR1, isoform CRA_b",1.005138
375128,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,0.946968,...,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0,NaN,uPA,1.013745
375129,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,0.946968,...,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0,NaN,vWF,1.004912

In [10]:
# Position the 4th last column to the first, and remove the columns that follow
second_trimester_model2 = second_trimester_model[[second_trimester_model.columns[-3]] + list(second_trimester_model.columns[:-3])] 
third_trimester_model2 = third_trimester_model[[third_trimester_model.columns[-3]] + list(third_trimester_model.columns[:-3])]
third_trimester_model2

,GA_delivery,Accession,14-3-3,17-beta-HSD 1,3HIDH,4-1BB,4-1BB ligand,40S ribosomal protein SA,41,4EBP2,...,sTie-1,sTie-2,suPAR,tPA,tau,"transcription factor MLR1, isoform CRA_b",uPA,vWF,GEO_accession,Group
0,40.1,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,...,1.018203,1.031849,1.003253,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0
1,40.1,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,...,1.018203,1.031849,1.003253,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0
2,40.1,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,...,1.018203,1.031849,1.003253,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0
3,40.1,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,...,1.018203,1.031849,1.003253,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0
4,40.1,GSM4525406,0.854517,1.050371,1.018176,1.014938,1.038545,1.051294,1.000397,1.031031,...,1.018203,1.031849,1.003253,0.970284,1.045365,1.005728,1.017679,0.997934,GSE150167,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375125,NaN,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,...,1.014591,1.032756,1.019477,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0
375126,NaN,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,...,1.014591,1.032756,1.019477,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0
375127,NaN,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,...,1.014591,1.032756,1.019477,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0
375128,NaN,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,...,1.014591,1.032756,1.019477,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0
375129,NaN,GSM6254832,0.849311,1.049217,1.025670,1.010858,1.032947,1.052785,0.998354,1.036671,...,1.014591,1.032756,1.019477,0.967156,1.055996,1.005138,1.013745,1.004912,GSE206454,0